### ISSUE TITLE
[PE-D][Tester E] Additional measure for "clear" command.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-3/tp#117]
![image.png](https://raw.githubusercontent.com/proto-aiken-13/ped/main/files/fdbf91cb-eaa1-451e-b724-cb1182ed4dad.png)

Similar to the issue raised with regards to the issues surrounding a deletion command, utilizing a clear command may be highly problematic should one mindlessly/accidentally clear the data by accident.

Without an additional measure for security in the clear command, there can be the following issues with the usage.
1) Sometime after clearing data, I realize that there is one specific job application that I wanted to track to this day, but I have no means of retrieving it.
2) I accidentally type clear by sheer accident.

There should be a way to either a) retrieve the data I deleted by storing all the deleted data in a temporary cache. The simpler alternative is to again add b) an extra line to confirm if the user wants to clear everything, by giving him an avenue to at least think twice to remove all data.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: proto-aiken-13/ped#2

**Comment by CJ-Lee01** [comment]
Remarks: same as #115
