### ISSUE TITLE
[PE-D][Tester A] Allowed to enter a command of editing an organisation's OID

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-3/tp#123]
Edit organisation format: `Edits an organization.
Parameters: INDEX/ID [--name NAME] [--id ID] [--phone PHONE] [--email EMAIL] [--url URL] [--address ADDRESS] [--tag TAG]...`

When `Edit 1 --oid randomorg` is entered, 
`Edited organization: Biopolis; Id: alex_yeoh_inc; Phone: 93941323; Email: contact@alexyeoh.example.com; Url: URL.com; Address: (none); Tags: [parttime]` is outputted, indicating to the user that the contact has been edited, when nothing has been changed or should not even be allowed to enter such a command.

![image.png](https://raw.githubusercontent.com/Jweewee/ped/main/files/3bb5f103-9520-4e66-9eda-b378443f05ff.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jweewee/ped#1

**Comment by wxwern** [comment]
Related to #128
