### ISSUE TITLE
[PE-D][Tester E] Add a glossary to the UG.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-3/tp#124]
The User Guide uses quite a lot of technical jargon to explain commands. I assume that your application is curtailed for all prospective job and internship applicants.

Users that are not from SOC (and I would argue that some students in SOC) may find the technical jargon very confusing to refer to and this may impede the User Guide's utility as a quick and easy guide for users.

I suggest adding a glossary to make the features and explaining the technical jargon for users to make it easier for them to understand the commands and some terms.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: proto-aiken-13/ped#4

**Comment by McNaBry** [comment]
Closed by #163
