### ISSUE TITLE
[PE-D][Tester A] Editing applications, organisations and recruiters and passing in an invalid parameter related to that type, is allowed as long as one valid field is also edited``

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-3/tp#128]
`Edited job application: {title=20203, 
stage=resume, 
status=pending, 
deadline=15-12-2023, 
description=None}` outputted when editing job application:
`edit --application 1 --title bugsquasher --tag NOThelpful`

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jweewee/ped#3

**Comment by wxwern** [comment]
A better summary of #125

**Comment by wxwern** [comment]
Could be considered both a bug and a flaw - non-applicable flags are validated already but not all of them are per subcategory of a command.
