### ISSUE TITLE
[PE-D][Tester E] Issue in table formatting for pre-determined issues.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W08-3/tp#129]
![image.png](https://raw.githubusercontent.com/proto-aiken-13/ped/main/files/40d59bd0-1662-40f5-a6ef-7722018453e6.png)

The requirements of `APPLICATION STAGE` and `STATUS` look oddly formatted. Under this format/layout, users may not immediately get the idea that the pre-determined stages are all the other values in the cell and is ambiguously left to the first cell i.e. they may only think that the `APPLICATION STAGE` requirement should be resume-only, as the first of three stages.

This looks to be a formatting issue, please do consider amending this to look make it look more clear to the user.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: proto-aiken-13/ped#6

**Comment by McNaBry** [comment]
Fixed via restructure of content and style changes.
