### ISSUE TITLE
[PE-D][Tester A] Wrong error message handling fields when applying to jobs`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-3/tp#135]
`apply 1 --title=fullstack` gives output
`Id should only contain alphanumeric characters, underscores and dashes, and it should not be blank. Ids must also start with alphabets, and may not have consecutive underscores and/or dashes.` indicating that id is wrong when it is not.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jweewee/ped#5

**Comment by wxwern** [comment]
Internally, `1 --title=fullstack` is parsed as the ID, as `--title` does not allow for an `=` after it, only space.

Additional documentation is needed to clarify on allowed formats (like parameter names like `--title` MUST be surrounded by whitespace), and improved error messages should be included as future work.
